# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Idp < Formula
  desc "Internal Developer Platform — globally installable demo"
  homepage "https://github.com/SrimanMayandi02/idp"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SrimanMayandi02/idp/releases/download/v0.1.2/idp_0.1.2_darwin_amd64.tar.gz"
      sha256 "f59e0a8e05f378c6884384d8700494529d484770d62138fde704a5e67195ba96"

      define_method(:install) do
        bin.install "idp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SrimanMayandi02/idp/releases/download/v0.1.2/idp_0.1.2_darwin_arm64.tar.gz"
      sha256 "ffca5f2dae2c45b0e7ce052f5c2a4c9f0cf2c204833d788c22b4815c3c5cbea0"

      define_method(:install) do
        bin.install "idp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SrimanMayandi02/idp/releases/download/v0.1.2/idp_0.1.2_linux_amd64.tar.gz"
      sha256 "c97d4051ecaf4f14afc772997b783459515f3067fc3e0290956e89c067584375"
      define_method(:install) do
        bin.install "idp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SrimanMayandi02/idp/releases/download/v0.1.2/idp_0.1.2_linux_arm64.tar.gz"
      sha256 "0cc1178e4416cbf5eec2e2dea6a5bd2d76e046fe244f0c3d6e3e8c2383892600"
      define_method(:install) do
        bin.install "idp"
      end
    end
  end

  test do
    system "#{bin}/idp"
  end
end
